### ISSUE TITLE
Interest in boost port to cmake

### ISSUE THREAD

**Issue by Manu343726** [flexferrum/Jinja2Cpp#38]
Hi,

Recently I [forked your project](https://github.com/Manu343726/Jinja2Cpp) to use [boost-cmake](https://github.com/boost-cmake/boost) as aubmodule. Boost-cmake is a full port of boost to cmake, with one cmake target per boost lib. I've also forked boost-cmake to ensure only the required libraries are configured.

Both forks are working (except unit tests) and I'm [already using them](https://gitlab.com/Manu343726/tinyrefl/pipelines/30578413) for my project.

I would like to know if you would be interested in adopting this boost-cmake aubmodule into your project, so Jinja2Cpp no longer relies on system dependencies (the main reason why I patched your library).

**Comment by flexferrum** [comment]
Hi Manuel,

Thanks for your interesting for my project. I aim it directly on the tool like yours and mine (which is similar to your). Now, regarding to your question:

> I would like to know if you would be interested in adopting this boost-cmake aubmodule into your project, so Jinja2Cpp no longer relies on system dependencies (the main reason why I patched your library).

My first thought was to answer 'no', because I prefer not to stick to the particular versions of libraries in case of boost and similar widely-used ones (may be I wrong here). And there was also another reason: now boost::variant is in the library public interface and I afraid of possible ABI mismatch on the library boundaries.

But then I understood that I've decided to remove boost from the public interface (I'm [replacing it](https://github.com/flexferrum/Jinja2Cpp/tree/nonstd_variant) with nonstd::variant by @martinmoene ). **So, I see no problem for now to stick on particular version of boost like you've done.** Also I appreciate your work on warnings cleanup in Jinja2Cpp, and I'd merge your corresponding PR with pleasure. I'm planning this work on the release 1.0 of the library, but you did it first. Thanks!

**Comment by flexferrum** [comment]
@Manu343726 ?

**Comment by Manu343726** [comment]
Sorry, I forgot to answer here.

Right now the integration of my work in my project seems stable, so if you think the fork could be merged in its current state I will PR as soon as possible

**Comment by flexferrum** [comment]
JFYI. I'm ready for merge
https://github.com/flexferrum/Jinja2Cpp/compare/nonstd_variant?expand=1

**Comment by Manu343726** [comment]
Merge that first and I will rebase, I have to fix some config flags first.

BTW, after that merge what would be your boost dependencies? filesystem?

**Comment by flexferrum** [comment]
OK.

> BTW, after that merge what would be your boost dependencies? filesystem?
filesystem, string algo, variant internals (recursive_wrapper), optional, system (for filesystem)

**Comment by flexferrum** [comment]
Done
#43

**Comment by Manu343726** [comment]
My GCC5.4 build does not compile after rebasing master:

```
[  3%] Built target boost_atomic
[  6%] Built target boost_system
[ 37%] Built target boost_regex
[ 55%] Built target boost_filesystem
[ 58%] Built target boost_exception
[ 68%] Built target boost_container
[ 72%] Building CXX object CMakeFiles/jinja2cpp.dir/src/expression_evaluator.cpp.o
In file included from /home/manuel/Documents/Jinja2Cpp/include/jinja2cpp/value.h:11:0,
                 from /home/manuel/Documents/Jinja2Cpp/src/internal_value.h:4,
                 from /home/manuel/Documents/Jinja2Cpp/src/expression_evaluator.h:4,
                 from /home/manuel/Documents/Jinja2Cpp/src/expression_evaluator.cpp:1:
/home/manuel/Documents/Jinja2Cpp/thirdparty/nonstd/value-ptr-lite/include/nonstd/value_ptr.hpp:377:45: er
ror: expected primary-expression before ‘)’ token
     T * operator()( nonstd_lite_in_place_t(T), Args&&... args ) const
                                             ^
/home/manuel/Documents/Jinja2Cpp/thirdparty/nonstd/value-ptr-lite/include/nonstd/value_ptr.hpp:377:45: er
ror: there are no arguments to ‘nonstd_lite_in_place_t’ that depend on a template parameter, so a declara
tion of ‘nonstd_lite_in_place_t’ must be available [-fpermissive]
/home/manuel/Documents/Jinja2Cpp/thirdparty/nonstd/value-ptr-lite/include/nonstd/value_ptr.hpp:377:45: no
te: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is 
deprecated)
/home/manuel/Documents/Jinja2Cpp/thirdparty/nonstd/value-ptr-lite/include/nonstd/value_ptr.hpp:377:52: er
ror: expected primary-expression before ‘&&’ token
     T * operator()( nonstd_lite_in_place_t(T), Args&&... args ) const
```

**Comment by flexferrum** [comment]
git submodule update --init

**Comment by Manu343726** [comment]
I would say there's a branch of the value_ptr std emulation config that is not defined for this case, and no definition of the macro `nonstd_lite_in_place_t()` is done.

**Comment by flexferrum** [comment]
Let's call to @martinmoene

**Comment by Manu343726** [comment]
Yep

**Comment by Manu343726** [comment]
Maybe I resolved a conflict in the .gitmodules file wrong... (I see value_ptr is pointing to yoyr fork)

**Comment by flexferrum** [comment]
May be. Try to point to my fork.

**Comment by Manu343726** [comment]
Fixed, my submodules where pointing to the wrong commits.

**Comment by flexferrum** [comment]
#56

**Comment by flexferrum** [comment]
Fight! :) 

https://github.com/kwallner/Jinja2Cpp/commit/c7d6c8ee7240d899f4a23e27ab1cd8444f60fd28
