### ISSUE TITLE
Callables values in templates

### ISSUE THREAD

**Issue by Manu343726** [flexferrum/Jinja2Cpp#39]
After looking through the library I'm pretty sure your implementation doesn't support callables in templates.

Do you think that this could be hard to implement right now?

**Comment by Manu343726** [comment]
Edit: just found call expression evaluation functions as part of your expression evaluation module, but there's no mention about it in the readme nor any unit test or example referencing callable expressions.

Is this feature WIP or I could start playing with it right now? In case the feature is ready, what would be the process to expose a function? Are C++ callables convertible to jinja2::Values so I can add functions to my values map or as part of the reflection of my types?

**Comment by flexferrum** [comment]
I guess, you request for something like this:
https://github.com/flexferrum/Jinja2Cpp/blob/a2ee7436c1e5213170278ca8184721236ae20fb7/include/jinja2cpp/value.h#L96

I'm going to add this feature with this branch. Engine internals are ready for call expressions, it's only need to be connected with public interface.

But some reflection glue needs to be written for smooth connection of any C++ callable to Jinja2, which follows the python rules of call. I mean some generic code which can convert FunctionCallParams to actual callable params.

**Comment by flexferrum** [comment]
"One doesn't simply call user-provided callable from Jinja2 expression" (Boromir face should be here) :)
In your example, you can call `foo` either as `{{ foo('hello') }}` or as `{{ foo(str='hello') }}`. If `foo` takes two args, you can provide both by name, both as positional, only one by name, etc. And, honesty, I don't want to break this rule.  It will be too error-prone. So now I'm looking for a way to keep this rule also for user-provided callables. I've got some thoughts about it, but I need hardware keyboard to describe them properly.

**Comment by flexferrum** [comment]
Ok. I've got my HW keyboard and able to explain my point of view on this problem. When user wants to pass callable into Jinja2Cpp he writes something like this:
```c++
params["foo"] = MakeCallable([](const std:;string& str) {return str + "!!!";}, ParamInfo{"str"});
```
`MakeCallable` prepares the special object which contains actual callable and information about params:
```c++
struct UserCallArgs
{
    ValuesMap args;
    ValuesList extraPosArgs;
    ValuesMap extraKwArgs;
};

struct ParamInfo
{
   std::string paramName;
   bool isDefault;
   Value defVal;

   ParamInfo(std:;string name, bool def = true, Value defVal = Value()) //...
};

struct UserCallable
{
    std::function<Value (const UserCallArgs&)> callable;
    std::vector<ParamInfo> paramsInfo;
};

template<typename Callable, typename ... T>
UserCallable MakeCallable(Callable&& fn, T ... paramsInfo)
{
    UserCallable result = {
        [f = std::forward<Callable>(fn), =](const UserCallArgs& args) {return InvokeUserCallable(f, args, paramsInfo...);}.
        {paramsInfo...}
    };

   return result;
}
```
and then `Invoke` function utilize `(non)std::visit` for args type conversion from abstract `Value` to callable-specific.

**Comment by Manu343726** [comment]
> and then Invoke function utilize `(non)std::visit`

Forgot completely about the multi-visitor, you're right, that would simplify the invocation a lot.

**Comment by flexferrum** [comment]
So, finally, `Invoke` can look like this:
```c++
Value::Data GetArg(const UserCallArgs& args, const ParamInfo& pInfo)
{
   auto p = args.args.find(pInfo.name);
   if (p != args.args.end())
      return p->second.Data();

   assert(pInfo.isDefault);
   return pInfo.defVal.Data();
}

template<typename Callable, typename ... PInfo>
Value Invoke(Callable&& fn, const UserCallArgs& args, const PInfo& ... pInfo)
{
    return nonstd::visit(Caller(fn), GetArg(args, pInfo)...);
}
```
and multi-visitor as a `Caller` (with some tricks I've learned from another my project). In this way of implementation I can use param mapping function from Jinja2Cpp internals and provide for template writers uniform way of calling any callable object (macro, filter, tester, user-defined function, etc.).

**Comment by flexferrum** [comment]
> you're right, that would simplify the invocation a lot.
@Manu343726 Yes. The code is simplified. :) 

https://github.com/flexferrum/Jinja2Cpp/blob/157eadeda9882d83c2ae82974bb21586366b1831/include/jinja2cpp/user_callable.h#L19
