### ISSUE TITLE
Custom filters: Callables? Macros?

### ISSUE THREAD

**Issue by Manu343726** [flexferrum/Jinja2Cpp#50]
When writing my templates I've found myself following this pattern: Take a list, transform its elements in some way, render as a joined list.

An example:

``` jinja2
{{list | map(attribute='first') | join(', ')}}
```

while this works when the transformation is just getting a member of each element of the list, I wonder if there's a way to apply this pattern with any kind of mapping. Say I have a macro named `hash()` that gets the hash of a string:

``` jinja2
{% macro hash(str) -%}
{{<compute hash here>}}
{%- endmacro %}
```

and I use it as follows:

``` jinja2
{{list_of_strings | hash | join(', ')}}
```

is this possible?

If that doesn't work with macros (i.e. using macros as filters), with the wip user-defined-callables from the C++ side, would I be able to use a callable as an user-defined filter?:

``` cpp
variables["hash"] = MakeCallable([](const std::string& str) {
    return std::hash<std::string>{}(str);
}, ArgInfo{"str});
```
``` jinja2
{{list_of_strings | hash | join(', ')}}
```

**Comment by Manu343726** [comment]
BTW The first case (using a macro as filter) must be doable with the second:

``` cpp
variables["macro_filter"] = MakeCallable([](const std::string& macro_name) {
    return MakeCallable([macro_name](const jinja2::Value& arg) {
        jinja2::Template tml;
        // load context from parent template here
        tml.Load("{{" + macro_name  + "(arg)}});
        return tml.RenderAsString({{"arg", arg}});
    }, ArgInfo{"arg"});
}, ArgInfo{"macro_name"});
```

here the `macro_filter` callable returns a callable taking one generic argument. This second callable returned from the first is the one that acts as filter.

*I'm supposing a filter expression is just a function application:*

``` cpp
jinja2::Value apply_filter(const jinja2::Value& data, const jinja2::Value& filter)
{
    jinja2::Value result;

    if(data.is_list())
    {
        for(const jinja2::Value& item : data)
        {
            result.as_list().append(apply_filter(item, filter));
        }
    }
    else
    {
        result = invoke_callable(filter, item);
    }

    return result;
}
```

**Comment by Manu343726** [comment]
The reason why I want macros as filters if that I like to keep all the logic in the template (So customizable behavior just depends on the template). As filters because in most cases all I do is data transformation until I have it in the format I want.

The alternative would be to join the lists manually, which is error-prone and time-consuming. See https://github.com/Manu343726/siplasplas/tree/master/src/reflection/parser/templates for an example of that.

**Comment by Manu343726** [comment]
Here's an example of the kind of template code I want to avoid to write (again xD):

``` cpp
{% macro overloaded_method(class, method_family) -%}
::cpp::static_reflection::codegen::OverloadedFunction<
{% for method_ in method_family %}
    {{method(class, method_) | indent(4)}}
{% if not loop.last %}
    ,
{% endif %}
{% endfor %}
>
{%- endmacro %}
```

*From https://github.com/Manu343726/siplasplas/blob/master/src/reflection/parser/templates/static_reflection_codegen_instances.jinja2*

Note how the macro contains a loop that invokes another macro for each element. The result of the nested macro invocation is a list of formatted items (method metadata in the example) that are manually joined with `', '`.

**Comment by flexferrum** [comment]
There is also the third way. Add special filter 'applymacro' with macro name and params as parameters. So, in template it will look somehow like this:
```
{% macro hash(str) -%}
{{<compute hash here>}}
{%- endmacro %}

...

{{list_of_strings | map('applymacro', name='hash') | join(', ')}}
```

**Comment by Manu343726** [comment]
That looks perfect to me, but I don't want to overload you with requests!

**Comment by flexferrum** [comment]
Meditating on the code like this:
```
{% macro joined(seq, delimiter=', ') -%}
{{ seq | map('applymacro' name='caller') | join(delimiter) }}
{%- endmacro %}

{% macro overloaded_method(class, method_family) -%}
::cpp::static_reflection::codegen::OverloadedFunction<
{%- call(method) joined(method_family) %}{{ method(class, method_) | indent(4) }}{% endcall -%}
>
{%- endmacro %}
```

**Comment by Manu343726** [comment]
So it's like this (The example form the call block docs):

``` jinja2
{% macro dump_users(users) -%}
    <ul>
    {%- for user in users %}
        <li><p>{{ user.username|e }}</p>{{ caller(user) }}</li>
    {%- endfor %}
    </ul>
{%- endmacro %}

{% call(user) dump_users(list_of_user) %}
    <dl>
        <dl>Realname</dl>
        <dd>{{ user.realname|e }}</dd>
        <dl>Description</dl>
        <dd>{{ user.description }}</dd>
    </dl>
{% endcall %}
```

but using a filter instead of a manual loop.

**Comment by Manu343726** [comment]
are call blocks currently implemented?

**Comment by flexferrum** [comment]
> are call blocks currently implemented?

Yes. But I'm considering now: could they be called in filter context or not. From the logical point of view.

**Comment by flexferrum** [comment]
@Manu343726 , it works!
https://github.com/flexferrum/Jinja2Cpp/blob/1f61cd9beebbe35278e2990bb97abdfff516162e/test/filters_test.cpp#L73
