### ISSUE TITLE
Jinja2Cpp not respecting space control in blocks

### ISSUE THREAD

**Issue by Manu343726** [flexferrum/Jinja2Cpp#64]
To avoid introducitng newlines when using multiline macros like this:

``` jinja2
{% macro my_macro(arg) -%}
hello world {{arg}}
{%- endmacro %}
```

Jinja2 allows putting +/- signs in blocks to control whether the trailing newlines and spaces in the macro should be rendered. In the example above, a call like `{{my_macro('hi')}}` should result in the string `"hello world hi"`, with no newlines.

If I write my macros using that control syntax, Jinja2Cpp ignores them and adds a newline to the end of the macro expansion: `"hello world hi<line jump here>"`

**Comment by flexferrum** [comment]
What if you put the space after `{{arg}}`?

**Comment by flexferrum** [comment]
Actually, there are number of tests for this feature, started from here:
https://github.com/flexferrum/Jinja2Cpp/blob/540086dcdd82edddf861eba0c1d0d966c0f7ed5e/test/basic_tests.cpp#L119

Seems like not all cases covered.

**Comment by Manu343726** [comment]
See https://gitlab.com/Manu343726/tinyrefl/-/jobs/105378187:

```
1: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1: tinyrefl-tool-tests is a Catch v2.0.1 host application.
1: Run with -? for options
1: 
1: ---------------------------------------------------------------------------------------------------
1: templates::macro_based_codegen::model
1:   macro defined in parent template
1: ---------------------------------------------------------------------------------------------------
1: ../tool/tests/templates/macro_based_codegen/model.cpp:170
1: ...................................................................................................
1: 
1: ../tool/tests/templates/macro_based_codegen/model.cpp:97: FAILED:
1:   CHECK( render == expected_render )
1: with expansion:
1:   "TINYREFL_STRING(foo)
1:   "
1:   ==
1:   "TINYREFL_STRING(foo)"
1: with messages:
1:   root: "/builds/Manu343726/tinyrefl/tool/templates/macro_based_codegen"
1:   With template: 
1:   {% extends "model.jinja2" %}{% block body %}{{tinyrefl_string('foo')}}{% endblock body %}
1: 
1: [simple file parser] [info] parsing file '/builds/Manu343726/tinyrefl/tool/tests/class.hpp'
1: ---------------------------------------------------------------------------------------------------
1: templates::macro_based_codegen::model
1:   file include guard
1: ---------------------------------------------------------------------------------------------------
1: ../tool/tests/templates/macro_based_codegen/model.cpp:175
1: ...................................................................................................
1: 
1: ../tool/tests/templates/macro_based_codegen/model.cpp:97: FAILED:
1:   CHECK( render == expected_render )
1: with expansion:
1:   "TINYREFL_TOOL_GENERATED__builds_Manu343726_tinyrefl_tool_tests_class.hpp_INCLUDED
1:   "
1:   ==
1:   "TINYREFL_TOOL_GENERATED__builds_Manu343726_tinyrefl_tool_tests_class.hpp_INCLUDED"
1: with messages:
1:   root: "/builds/Manu343726/tinyrefl/tool/templates/macro_based_codegen"
1:   With template: 
1:   {% extends "model.jinja2" %}{% block body %}{{include_guard(file)}}{% endblock body %}
1: 
1: ===================================================================================================
1: test cases:  3 |  2 passed | 1 failed
1: assertions: 12 | 10 passed | 2 failed
```

**Comment by flexferrum** [comment]
OK, I'll check it.

**Comment by flexferrum** [comment]
Hm... Jinja2 doc is quite confuse and not straight forward. When I implemented space stripping functionality I follow the `lstrip_blocks` rule:
> _lstrip_blocks_
If this is set to True leading spaces and tabs are stripped **from the start of a line to a block**. Defaults to False. 

Both for flag and for `-` sign just after `{{` or `{%`. But, actually, there is different behavior for environment flag and `-` space trimming control sign. The second one is removed all spaces:

> ```jinja
{% for item in seq -%}
    {{ item }}
{%- endfor %} ```
This will yield all elements without whitespace between them. If seq was a list of numbers from 1 to 9, the output would be 123456789.

**Comment by flexferrum** [comment]
https://github.com/flexferrum/Jinja2Cpp/commit/a146f5bdae19d6fe2eff165f03ccf20cde4ddce8

**Comment by Manu343726** [comment]
My tests look green after that change, Thanks a lot.

**Comment by flexferrum** [comment]
Great!
