### ISSUE TITLE
More generic mapping interface for field reflection

### ISSUE THREAD

**Issue by Manu343726** [flexferrum/Jinja2Cpp#67]
Basically, instead of returning a map, implement a simple getField(name) hasField(name) fieldNames() etc interface.

This hides the underlying user map of fields, which opens the door for simple reflection of arbitrary data structures, like json objects for example.

**Comment by flexferrum** [comment]
This is how object reflection works:
https://github.com/flexferrum/Jinja2Cpp/blob/a146f5bdae19d6fe2eff165f03ccf20cde4ddce8/include/jinja2cpp/reflected_value.h#L41

Actually, this is GenericMap implementation over the std::unordered_map (and some CRTP :) )

**Comment by Manu343726** [comment]
but in that code I don't see a way to implement the generic map interface for my user defined type. Like:

``` cpp
template<>
struct TypeReflection<JSON>
{
    jinja2::Value getValueByName(const JSON& json, const std::string& name)
    {
        return jinja2::Reflect(json[name]);
    }

    ...
};
```

**Comment by flexferrum** [comment]
Hm... It should look something like this:

```c++
namespace jinja2::detail
{
struct JsonReflector : public MapItemAccessor
{
   jinja2::Value getValueByName(const std::string& name)
    {
        return jinja2::Reflect(m_value[name]);
    }

   //... Other interface methods go here

   JSON m_value;
};

template<typename T>
struct Reflector<JSON>
{
    static auto Create(JSON val)
    {
        return JsonReflector::CreateFromValue(std::move(val));
    }
    static auto CreateFromPtr(const std::set<T>* val)
    {
        return JsonReflector::CreateFromPtr(val);
    }
};
}

**Comment by Manu343726** [comment]
EUREKA, now I got it. So you specialize the Reflector directly instead of TypeReflection, and use a custom implementation of the map interface for my type. Everything in the `jinja2::detail` namespace.

**Comment by flexferrum** [comment]
Yes. `TypeReflection` is only for arbitrary C++ types reflection.
