### ISSUE TITLE
Use cmake to handle thirdparty deps

### ISSUE THREAD

**Issue by Manu343726** [flexferrum/Jinja2Cpp#68]
Long story short: I hate git submodules. They're a pain to keep up to date, to touch, and generate issues when merging different branches.

I propose removing the submodules and using CMake instead to download the dependencies. There are two options:

 - [DownloadProject.cmake](https://github.com/Crascit/DownloadProject): This is a cmake module that implements git project download at configure time. After the download command you can `add_subdirectory()` the downloaded project source dir as if it was part of your project. See [here](https://github.com/Manu343726/tinyrefl/blob/master/cmake/externals.cmake) and [here](https://github.com/Manu343726/tinyrefl/blob/jinja2-based-tool/tool/external/externals.cmake#L99) for an example of usage (That's how tinyrefl downloads thirdparty deps).
 - [CMake FetchContent module](https://cmake.org/cmake/help/git-stage/module/FetchContent.html): That's an standard cmake module very similar to (I don't know if it was inspired from) DownloadProject. This module is shipped with CMake >= 3.11, so using it would require Jinja2Cpp to require cmake >= 3.11.

Why?
 - **Updating dep sources is simple**: Just go to your cmake config and change the url, git tag, etc.
 - **Sources can be externally configured by the user**: You can parameterize every dep source url and version, so that users can override your default config. I did this with tinyrefl to allow me point some dependencies to our in-house git mirrors at work. 
 - **No recursive clone is needed**: CMake ensures dependencies are always set up.
 - **Integration with package managers is much simpler**: Since this uses cmake to handle deps, in the future adapting the library to support package managers and use this package managers to get lib dependencies could be just an `if()` in the dependencies cmake script:
    ``` cmake
    if(NOT JINJA2CPP_USING_CONAN)
        downloadproject(...)
        ...
    else()
        include(conanbuildinfo.cmake)
        set(dependencies ${CONAN_LIBS})
    endif()
    ````
 while at the same time we could keep the cmake deps download for backwards compatibility (i.e. Don't make Jinja2Cpp unusable without conan etc).

**Comment by Manu343726** [comment]
FYI wip conan recipe https://gitlab.com/Manu343726/jinja2cpp-conan

**Comment by Manu343726** [comment]
https://gitlab.com/Manu343726/conan-nonstdlite-packages recipes for lite libraries

**Comment by Manu343726** [comment]
@flexferrum your lite dependencies are variant, optional, value-ptr, and expected, right?

**Comment by flexferrum** [comment]
Right. 'optional' not yet integrated, but the list is correct.

**Comment by Manu343726** [comment]
alright. so these four lite libs plus boost::filesystem, boost::algorithm, boost::variant (which will be replaced by variant-lite in the future), boost::optional (replaced by optional-lite)?

**Comment by flexferrum** [comment]
gtest

**Comment by Manu343726** [comment]
that's for testing only, I have it disabled for now

**Comment by Manu343726** [comment]
@flexferrum please review this https://github.com/Manu343726/Jinja2Cpp/commit/19f549f245a8324eb90d465c1e8bd90294475a8c

It's a full rewrite of the handling of Jinja2Cpp dependencies to:

 - Use standard `find_package()` calls to find deps. This works if you're pulling dependencies from the system, a package manager (conan with its cmake_find_package generator), etc.
 - If no package is found, fallback to submodules.

**Comment by Manu343726** [comment]
@flexferrum follow up: https://github.com/Manu343726/Jinja2Cpp/commit/5fa7aa0c0bf9a63fcfb67ce3fe0c0f29275dbf58

**Comment by Manu343726** [comment]
I think we could close this issue if we merge those changes.

**Comment by Manu343726** [comment]
Damn, it seems that its not possible to write an alias library target to an imported lib...

**Comment by flexferrum** [comment]
> Damn, it seems that its not possible to write an alias library target to an imported lib...

Really? O_o

**Comment by Manu343726** [comment]
yes... see https://github.com/Manu343726/Jinja2Cpp/commit/32cb043d4df31bf2d54100e2a486c708726cbd5b

**Comment by flexferrum** [comment]
#81
