### ISSUE TITLE
Do not override/ignore user boost dependencies

### ISSUE THREAD

**Issue by Manu343726** [flexferrum/Jinja2Cpp#69]
Just noticed there's a potential bug in the boost dependency. Right now, the boost module takes a list `BOOST_CMAKE_LIBRARIES` to configure the required libraries only. So Jinja2Cpp  sets this list to its set of boost dependencies.

Now me, as a jinja2cpp user, I want to use a couple more boost libs. By following the cmake-fetch-content rules, only the first dependant project downloads the dependency, but that dependency could be used by multiple projects in the project tree. That means that any dependent project, not just one, should be able to request something from the dependency. 

With our current setup, this is not true since we are hardcoding the `BOOST_CMAKE_LIBRARIES` manually. The solution is simple (I'm writing down everything here since I cannot fix this right now):

 - Use `list(APPEND)` to add boost libraries to the list. This is a simple change at the jinja2cpp level.
 - Make user the list does not contain duplicates. This requires touching the boost-cmake CMakeLists.txt script to run a remove duplicates before populating the targets.

After the fix jinja2cpp users should be able to request more boost libraries, like this:

``` cmake
list(APPEND BOOST_CMAKE_LIBRARIES coroutine2 fiber)
add_subdirectory(jinja2cpp)
...
```

**Comment by Manu343726** [comment]
If I were you I would tag this as bug, and assign the issue to me. I will send you a PR asap.

**Comment by Manu343726** [comment]
Of course all this would not happen if we were using a proper package manager, but that's a different battle that I have no time to participate right now...

**Comment by flexferrum** [comment]
> If I were you I would tag this as bug, and assign the issue to me. I will send you a PR asap.

Done

> Of course all this would not happen if we were using a proper package manager, but that's a different battle that I have no time to participate right now...

conan.io integration is preparing by the another person: https://github.com/kwallner/Jinja2Cpp/commit/c7d6c8ee7240d899f4a23e27ab1cd8444f60fd28

Where is some discussion behind this commit about the estimates.

**Comment by flexferrum** [comment]
#81
