### ISSUE TITLE
Dockerfile Project Help Needed

### ISSUE THREAD

**Issue by DragonOsman** [flexferrum/Jinja2Cpp#70]
I need some help on a Dockerfile project based on the app I made (the same currency converter one).  I also had a similar problem with Nlohmann.JSON, so I opened an issue there as well.  When I tried to build the image using my Dockerfile, even though I have `RUN` commands to download (and build) the needed dependencies, I got an error on Nlohmann.JSON and Jinja2Cpp saying that certain files can't be found.  For Jinja2Cpp, there was an error from CMake saying that the directory `/app` doesn't have a `CMakeLists.txt` file (`/app` is the root directory for the app within the Docker image, and it'll only exist inside the image).  

The C++ code that has to be compiled is also on GitHub, so I'll just put the GitHub link here: https://github.com/DragonOsman/currency_converter/blob/master/currency_converter.cpp .  

Edit: I decided I'll try to compile the code directly on my Bionic Beaver VM and then put the executable into the Dockerfile.  Seems like it'll be easier that way.  I just need to fix a compiler error I have right now.  I'll keep this open in case I can get a reply with a good way to fix the problem with building the Dockerfile.

**Comment by Manu343726** [comment]
do you have a link to your dockerfile, the script that builds your dockerfile, etc?
