### ISSUE TITLE
[thirdparty] Rename nonstd/*-light to nonstd/*-lite

### ISSUE THREAD

**Issue by martinmoene** [flexferrum/Jinja2Cpp#82]
Unless I'm missing some cue, perhaps prefer to use the canonical names `expected-lite` and `variant-lite` for `expected-light` and `variant-light` in folder `thirdparty/nonstd`.

**Comment by flexferrum** [comment]
Definitely. That's my typo. Will fix it.

**Comment by flexferrum** [comment]
Done: https://github.com/flexferrum/Jinja2Cpp/commit/ac84be983226367eba5eaf66c13c2c6cb10f81ba
