### ISSUE TITLE
windows-based clang++ linker errors - unresolved external symbol

### ISSUE THREAD

**Issue by DragonOsman** [flexferrum/Jinja2Cpp#89]
I have some "unresolved external symbol" errors from Jinja2Cpp when trying to compile my code using clang++ under the Developer Command Prompt for VS2017 shell.  Clang uses Microsoft's linker.exe in this case, so the errors are exclusive to MSVC's linker.  The errors are:
```
jinja2cpp.lib(expression_evaluator.obj) : error LNK2019: unresolved external symbol __imp_remainder referenced in function "public: class jinja2::InternalValue __cdecl jinja2::visitors::BinaryMathOperation::operator()(double,double)const " (??RBinaryMathOperation@visitors@jinja2@@QEBA?AVInternalValue@2@NN@Z)
jinja2cpp.lib(filters.obj) : error LNK2001: unresolved external symbol __imp_remainder
jinja2cpp.lib(testers.obj) : error LNK2001: unresolved external symbol __imp_remainder
jinja2cpp.lib(filters.obj) : error LNK2019: unresolved external symbol __imp_round referenced in function "public: class jinja2::InternalValue __cdecl jinja2::filters::ValueConverterImpl::operator()(double)const " (??RValueConverterImpl@filters@jinja2@@QEBA?AVInternalValue@2@N@Z)
currency_converter.exe : fatal error LNK1120: 3 unresolved externals
clang++.exe: error: linker command failed with exit code 1120 (use -v to see invocation)
```
The code is for the same app as before, except with async networking functions.  The code is here: https://github.com/DragonOsman/currency_converter/blob/master/currency_converter.cpp

Should I also ask on the MSDN community forums?  Anyway, yeah, if you know how to fix this, please help.

**Comment by flexferrum** [comment]
Several points here:
1. I'm not planning to support clang-based builds on windows in the near future
2. Jinja2Cpp haven't got clang-based build tests on windows and doesn't support it
2. Seems like this is not a bug in the Jinja2Cpp lib but in your project settings.

Most probably, you've built Jinja2Cpp with dynamic runtime library settings, but clang trying to link static runtime. That's a common problem for MSVC world.

**Comment by DragonOsman** [comment]
I have the .lib file for Jinja2Cpp in `install/lib/static`.  I'd say it's a static library.

**Comment by flexferrum** [comment]
It's a different and independent settings. You can build _static_ library with either _dynamic_ or _static_ MSVC runtime. You can change MSVC runtime type to static for Jinja2Cpp by providing `-DMSVC_RUNTIME_TYPE=/MT` switch in the cmake command line.
